###########################################################################################################################################################
# #########################################################

# Compila las clases del Banco, Cuenta y Titular 

# #########################################################

compile:
	javac *.java
	
	
# #########################################################

# Compila bancoClient 

# ########################################################
execute:
	java -Djava.security.policy=servidor.permisos -Djava.net.preferIPv4Stack=true -Djava.rmi.server.hostname=192.168.254.139 -cp postgresql-42.2.5.jar:./ ServidorJuegos 54321